#!/system/xbin/busybox ash
# "THE THING"
#Made by _Bon_Bon(@XDA)
#All parts of this MOD and all the code in it
#are protected by GNU GPL, version 3
#Copyright (C) 2015 Francisco Pulido Garces (_Bon_Bon)
#see <http://www.gnu.org/licenses/>
ifex () {
	if [ -e $4 ]; then $1 $2 $3 $4; fi
}
#-- Setting CPU governor to Ondemand
for i in cpu0 cpu1 cpu2 cpu3 cpu4 cpu5 cpu6 cpu7; do
	echo "ondemand" > /sys/devices/system/cpu/$i/*/scaling_governor
done
case $1 in
	-v) #Place here your version information
		echo "VERSION: 0.1b Made by _Bon_Bon" ;;
	PURE) #Place here your modified PURE profile tweaks
		#-- Tweaking the governor
		ifex echo "90" > /sys/devices/system/*/conservative/up_threshold
		ifex echo "2" > /sys/devices/system/*/conservative/sampling_down_factor
		ifex echo "10" > /sys/devices/system/*/conservative/freq_step
		ifex echo "10" > /sys/devices/system/*/conservative/freq_down_step
		ifex echo "75" > /sys/devices/system/*/conservative/down_threshold
		ifex echo "0" > /sys/devices/system/*/conservative/ignore_nice_load
		#-- Tweak I/O Scheduler
		echo "noop" > /sys/block/mmcblk0/queue/scheduler
		#-- Change TCP thingy
		sysctl -e -w net.ipv4.tcp_congestion_control=cubid
		#-- Change LMK Values
		echo "1024,2048,4096,8192,12288,16384" > /sys/module/lowmemorykiller/parameters/minfree
		#-- Change ADJ Values
		echo `cat /data/The_Thing/System/ADJBackUp.txt` > /sys/module/lowmemorykiller/parameters/adj
	;;
	MUSIC)
		#-- Tweaking the governor
		ifex echo "70" > /sys/devices/system/*/conservative/up_threshold
		ifex echo "3" > /sys/devices/system/*/conservative/sampling_down_factor
		ifex echo "15" > /sys/devices/system/*/conservative/freq_step
		ifex echo "15" > /sys/devices/system/*/conservative/freq_down_step
		ifex echo "55" > /sys/devices/system/*/conservative/down_threshold
		ifex echo "1" > /sys/devices/system/*/conservative/ignore_nice_load
		#-- Tweak I/O Scheduler
		echo "noop" > /sys/block/mmcblk0/queue/scheduler
		#-- Change TCP thingy
		sysctl -e -w net.ipv4.tcp_congestion_control=westwood
		#-- Change LMK Values
		echo "1024,2048,2560,4096,6144,8192" > /sys/module/lowmemorykiller/parameters/minfree
		#-- Change ADJ Values
		echo `cat /data/The_Thing/System/ADJBackUp.txt` > /sys/module/lowmemorykiller/parameters/adj
	;;
esac
