#!/system/xbin/busybox ash
# "THE THING"
#Made by _Bon_Bon(@XDA)
#All parts of this MOD and all the code in it
#are protected by GNU GPL, version 3
#Copyright (C) 2015 Francisco Pulido Garces (_Bon_Bon)
#see <http://www.gnu.org/licenses/>
ifex () {
	if [ -e $4 ]; then $1 $2 $3 $4; fi
}
#Start_Of_Changeable_Parameters
governor=Conservative
schedname=noop
tcpname=westwood
#End_Of_Changeable_Parameters
#-- Setting CPU governor to Ondemand
for i in cpu0 cpu1 cpu2 cpu3 cpu4 cpu5 cpu6 cpu7; do
	echo "$governor" > /sys/devices/system/cpu/$i/*/scaling_governor
done
#-- Tweaking the governor
if [ "$governor" = "Conservative" ]; then
	ifex echo "70" > /sys/devices/system/*/conservative/up_threshold
	ifex echo "3" > /sys/devices/system/*/conservative/sampling_down_factor
	ifex echo "15" > /sys/devices/system/*/conservative/freq_step
	ifex echo "15" > /sys/devices/system/*/conservative/freq_down_step
	ifex echo "55" > /sys/devices/system/*/conservative/down_threshold
	ifex echo "1" > /sys/devices/system/*/conservative/ignore_nice_load
else
	ifex echo "80" > /sys/devices/system/*/ondemand/up_threshold
	ifex echo "15" > /sys/devices/system/*/ondemand/down_differential
	ifex echo "1" > /sys/devices/system/*/ondemand/io_is_busy
	ifex echo "2" > /sys/devices/system/*/ondemand/sampling_down_factor
	ifex echo "30000" > /sys/devices/system/*/ondemand/sampling_rate
fi
#-- Tweak I/O Scheduler
echo "$schedname" > /sys/block/mmcblk0/queue/scheduler
#-- Change TCP thingy
sysctl -e -w net.ipv4.tcp_congestion_control=$tcpname
#-- Change LMK Values
echo `cat /data/The_Thing/System/OomBackUp.txt` > /sys/module/lowmemorykiller/parameters/minfree
#-- Change ADJ Values
echo `cat /data/The_Thing/System/ADJBackUp.txt` > /sys/module/lowmemorykiller/parameters/adj
}
